services:
    _defaults:
        autowire: true
        autoconfigure: true

    FH\Bundle\MakerBundle\Doctrine\EntityClassGenerator:
        $generator: '@maker.generator'
        $doctrineHelper: '@maker.doctrine_helper'
        
    FH\Bundle\MakerBundle\Maker\MakeEntity:
        arguments:
            $doctrineHelper: '@maker.doctrine_helper'
            $fileManager: '@maker.file_manager'
            $entityClassGenerator: '@FH\Bundle\MakerBundle\Doctrine\EntityClassGenerator'
